# Generated by Django 5.2.7 on 2025-12-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
