# Generated by Django 5.2.7 on 2025-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='jobtype',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='verifiedcompany',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='workformat',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AddField(
            model_name='currency',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobtype',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verifiedcompany',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workformat',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
