# Generated by Django 5.2.9 on 2025-12-04 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfinder', '0002_alter_currency_options_alter_jobtype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('cv_url', models.URLField(blank=True, help_text='Link to CV (Cloudinary or external)')),
                ('status', models.CharField(choices=[('pending', 'Chờ xử lý'), ('approved', 'Được chấp nhận'), ('rejected', 'Bị từ chối')], default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobfinder.form')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('form', 'applicant')},
            },
        ),
    ]
