# Generated by Django 5.2.7 on 2025-12-03 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cv_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
