# Generated by Django 5.2.7 on 2025-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_cv_profile_cv_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['order', 'code']},
        ),
        migrations.AddField(
            model_name='gender',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='status',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
