# Generated by Django 5.2.7 on 2025-12-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_gender_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(blank=True, help_text='Tailwind color classes', max_length=50),
        ),
        migrations.AddField(
            model_name='status',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name from lucide-react', max_length=50),
        ),
    ]
